Add nvidia shield 2017 controller
flightlessmango/MangoHud pull request #1318
Opened 2024-05-03 10:03 UTC by Arias800

This commit adds support for the Nvidia shield controller.
The controller has been natively supported in the Linux kernel since 6.5.

This commit only works for the 2017 version, the 2015 version is not compatible with Linux.

![Screenshot_20240503_120058](https://github.com/flightlessmango/MangoHud/assets/24809312/85923efd-d9c6-4260-b787-2fb3fac5d33b)

2024-05-07 03:45 UTC, gort818 requested changes
The check for "thunderstrike" should be  encapsulated in if (std::find(params.device_battery.begin(), params.device_battery.end(), "gamepad") != params.device_battery.end()){

2024-05-07 03:47 UTC, gort818 commented on src/device.cpp
> +        if (fileName.find("thunderstrike") != std::string::npos) {
Move this statement into the check for "gamepad" with the rest of the devices

2024-05-07 09:05 UTC, Arias800 commented
I have made the requested change.
I am sorry for the error.

2024-05-08 00:06 UTC, gort818 commented
No problem,  If you can squash commits ready to merge.
Thank you!

2024-05-08 09:19 UTC, Arias800 commented
I think I squashed everything correctly.
It's my first time doing this, so I hope I didn't mess anything up.

2024-05-08 22:52 UTC, merged

2024-05-08 22:52 UTC, gort818 commented
Looks good, Thanks again!